#!/usr/bin/env zsh

if [ $commands[cargo] ]; then
    cargo() {
        unfunction "$0"
        declare -A _comps
        autoload -Uz _cargo
        _comps[cargo]=_cargo
        echo "Completions Loaded!"
    }
fi

cargo