#!/usr/bin/env zsh

if [ $commands[rustup] ]; then
    rustup() {
        unfunction "$0"
        declare -A _comps
        autoload -Uz _rustup
        _comps[rustup]=_rustup
        echo "Completions Loaded!"
    }
fi

rustup