#!/usr/bin/env bash

# +--------+
# | System |
# +--------+

alias shutdown="sudo shutdown now"
alias restart="sudo reboot"
alias suspend="sudo pm-suspend"
alias sysinfo="inxi -Fxz"

# +-------+
# | FILES |
# +------+

alias ls="lsd -Fl"
alias lsa="lsd -Fl -a"
alias lst="lsd --tree --depth 3"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# +------+
# | GIT |
# +-----+

alias gitlog="git log --graph --oneline --decorate"
alias gitmod="git submodule sync && git submodule update --remote && git pull --recurse-submodules"
alias gita="git add ."

# +------+
# | MISC |
# +-----+

alias grep='grep --color=auto'
alias dockls="docker container ls | awk 'NR > 1 {print \$NF}'"      # display names of running containers
alias python="python3"
alias ts-node="npx ts-node"
alias hardhat="npx hardhat"
alias vpnc="protonvpn-cli connect"
alias vpnd="protonvpn-cli disconnect"
alias vpns="protonvpn-cli status"
alias mysql='sudo mysql -u root -p'
alias update='pip install --user --upgrade pipenv'
alias msql='mysql -u root -p --show-warnings'
# install terminfo for alacritty when ssh on server
alias aterminfo='wget https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info && tic -xe alacritty,alacritty-direct alacritty.info && rm alacritty.info'
alias dotfiles='git --git-dir=$HOME/.dotrepo/ --work-tree=$HOME'
