#!/usr/bin/bash

img=/tmp/i3lock.png
scrot -o $img
convert $img -scale 10% -scale 1000% $img

DARK='08080880'
PURPLE='#d183d8ff'
BLACK='#323437ff'
RED='#ff5454ff'
i3lock_options="--insidever-color=$DARK \
--ringver-color=$PURPLE \
\
--insidewrong-color=$DARK \
--ringwrong-color=$RED \
\
--inside-color=$DARK \
--ring-color=$BLACK \
--line-color=$BLACK \
--separator-color=$DARK \
--radius 100\
\
--wrong-text=403 \
--noinput-text=None \
--lock-text=Locking.. \
--verif-text=Wait.. \
--lockfailed-text=500
\
-i $img
--nofork
--show-failed-attempts
--ignore-empty-password
--centered
"

pre_lock() {
    dunstctl set-paused true

    xset +dpms dpms 30 30 30
    return
}

post_lock() {
    dunstctl set-paused false

    xset dpms 0 0 0
    xset dpms force on
    return
}


pre_lock

if [[ -e /dev/fd/${XSS_SLEEP_LOCK_FD:--1}]]; then
    kill_i3lock() {
        pkill -xu $EUID "$@" i3lock
    }
    trap kill_i3lock TERM INT

    i3lock $i3lock_options {XSS_SLEEP_LOCK_FD}<&-
    exec {XSS_SLEEP_LOCK_FD}<&-

    while kill_i3lock -0; do
        sleep 0.5
    done
else
  trap 'kill %%' TERM INT
  i3lock -n $i3lock_options &
  wait
fi

post_lock