#!/usr/bin/env bash
set -e

revert() {
    xset dpms 0 0 0
    xset dpms force on
    pkill -xu $EUID i3lock
}
trap revert EXIT

img=/tmp/i3lock.png

scrot -o $img
convert $img -scale 10% -scale 1000% $img

xset +dpms dpms 30 30 30

if [ -n "${XSS_SLEEP_LOCK_FD}" ] && [[ -e /dev/fd/${XSS_SLEEP_LOCK_FD:--1} ]]; then
    i3lock -ef -i $img -p default {XSS_SLEEP_LOCK_FD}<&-

    exec {XSS_SLEEP_LOCK_FD}<&-
else 
    i3lock -ef -i $img -p default
fi

tail --pid="$(pidof -s i3lock)" -f /dev/null
