#!/usr/bin/env zsh

function pip_gen() {
    if (( $+commands[pip3] )); then
        ver="$(pip3 --version)"
        ver_file="$ZDOTDIR/comps/pip/pip_version"
        comp_file="$ZDOTDIR/comps/pip/_pip_completion"
        mkdir -p "${comp_file:h}"
        if [[ ! -f "$comp_file" || ! -f "$ver_file" || "$ver" != "$(< "$ver_file")" ]]; then
            command rm -f "${0:A:h}/_pip_completion"
            pip3 completion --zsh >| "$comp_file"
            echo "$ver" >| "$ver_file"
        fi
   unset ver ver_file comp_file
   fi
}
