#!/usr/bin/perl

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;

if ($status eq 'Charging') {
	$full_text = ' ﮣ';
} elsif ($status eq 'Discharging') {
	if ($percent < 20) {
		$full_text = ' ';
	} elsif ($percent < 40) {
		$full_text = ' ';
	} elsif ($percent < 60) {
		$full_text = '  ';
	} elsif ($percent < 80) {
		$full_text = '  ';
	} elsif ($percent < 100) {
		$full_text = '  ';
	}
}

$full_text .="$percent% ";
print "$full_text\n";

exit(0);
